name: tmyv_deneg_web
description: "Практическая работа 5. Flutter Web: аутентификация, роли и защита маршрутов."
publish_to: "none"
version: 5.0.0+5

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  go_router: 17.2.3
  provider: ^6.1.2
  shared_preferences: ^2.5.3
  dio: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  http_mock_adapter: ^0.6.1

flutter:
  uses-material-design: true
